---
- name: Install MySQL
  apt:
    name: mysql-server
    state: present
  become: yes
  when: java_check.rc == 0


- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  when: java_check.rc == 0

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes


- name: Create MySQL ansible user
  mysql_user:
    name: ansible
    password: "{{ mysql_password }}"
    host: localhost
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes


- name: Remove insecure default users
  mysql_user:
    name: "{{ item }}"
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop:
    - 'root@localhost'
    - 'mysql.session@localhost'
  become: yes


- name: Flush MySQL privileges
  mysql_db:
    name: "{{ item }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  loop:
    - 'mysql'
    - 'information_schema'
  become: yes


